import { useEffect, useState } from "react";
import { weeklyAvailabilityApi } from "../../api/weekly-availability";

const days=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"];
export default function AvailabilityPageSelf(){
 const [schedule,setSchedule]=useState(Object.fromEntries(days.map(d=>[d,{start_time:d==="saturday"||d==="sunday"?null:"09:00",end_time:d==="saturday"||d==="sunday"?null:"17:30"}]))); const [timezone,setTimezone]=useState("Asia/Kolkata"); const [msg,setMsg]=useState("");
 useEffect(()=>{weeklyAvailabilityApi.getSchedule().then(r=>{if(r.schedule?.length){const next={...schedule};r.schedule.forEach(x=>next[x.day_of_week]={start_time:x.start_time?.slice(0,5)||null,end_time:x.end_time?.slice(0,5)||null});setSchedule(next);setTimezone(r.timezone||"Asia/Kolkata");}}).catch(()=>{});},[]);
 const save=async()=>{await weeklyAvailabilityApi.setup({timezone,schedule});setMsg("Availability saved successfully.");};
 return <div className="space-y-5"><div><h1 className="font-display text-2xl font-semibold">My Availability</h1><p className="text-sm text-muted">Configure all seven days. Leave days are applied separately after approval.</p></div><div className="bg-white border border-line rounded-lg p-5 space-y-3"><label className="text-sm font-medium">Timezone<select className="block mt-1 border rounded px-3 py-2" value={timezone} onChange={e=>setTimezone(e.target.value)}><option>Asia/Kolkata</option><option>UTC</option><option>Asia/Singapore</option></select></label>{days.map(d=><div key={d} className="grid grid-cols-3 gap-3 items-center border-t pt-3"><span className="capitalize font-medium">{d}</span><input type="time" className="border rounded px-2 py-2" value={schedule[d].start_time||""} onChange={e=>setSchedule({...schedule,[d]:{...schedule[d],start_time:e.target.value||null}})}/><input type="time" className="border rounded px-2 py-2" value={schedule[d].end_time||""} onChange={e=>setSchedule({...schedule,[d]:{...schedule[d],end_time:e.target.value||null}})}/></div>)}<button onClick={save} className="px-4 py-2 rounded bg-accent text-white">Save Availability</button>{msg&&<p className="text-sm text-green-700">{msg}</p>}</div></div>;
}
