"""
AI analysis of daily work updates.

Generated by:
- Gemini (if API key present)
- Rule-based analysis (fallback)
- ML models (future)

Results stored for audit trail and review.
"""
from datetime import datetime
import enum

from sqlalchemy import DateTime, ForeignKey, Text, String, Enum as SAEnum
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base


class RiskLevel(str, enum.Enum):
    """Risk assessment levels."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class AIProvider(str, enum.Enum):
    """Which system generated the analysis."""
    GEMINI = "gemini"
    RULE_BASED = "rule_based"
    ML_MODEL = "ml_model"


class DailyWorkUpdateAnalysis(Base):
    """
    AI-generated analysis of a daily work update.
    
    Identifies:
    - Completed items
    - Pending items
    - Detected blockers
    - Risk level
    - Suggested actions
    - Related tasks with status suggestions
    """
    __tablename__ = "daily_work_update_analysis"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    daily_update_id: Mapped[int] = mapped_column(
        ForeignKey("daily_work_updates.id"), nullable=False, index=True
    )

    # Analysis content
    summary: Mapped[str | None] = mapped_column(Text, nullable=True)  # Overall summary
    completed_items: Mapped[str | None] = mapped_column(Text, nullable=True)  # Structured list
    pending_items: Mapped[str | None] = mapped_column(Text, nullable=True)  # Structured list
    detected_blockers: Mapped[str | None] = mapped_column(Text, nullable=True)  # Identified issues

    # Risk assessment
    risk_level: Mapped[RiskLevel] = mapped_column(SAEnum(RiskLevel), nullable=False, default=RiskLevel.LOW)
    risk_reason: Mapped[str | None] = mapped_column(Text, nullable=True)  # Why this risk level?

    # Suggestions
    suggested_progress: Mapped[int | None] = mapped_column(nullable=True)  # Suggested % complete

    suggested_actions: Mapped[str | None] = mapped_column(Text, nullable=True)  # Recommended next steps
    task_suggestions: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON of task suggestions

    # Metadata
    ai_provider: Mapped[AIProvider] = mapped_column(SAEnum(AIProvider), nullable=False)
    model_version: Mapped[str | None] = mapped_column(String(100), nullable=True)  # e.g., "gemini-1.5-pro"

    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, nullable=False)
