export function AnalysisDisplay({ analysis }) {
  if (!analysis) {
    return null;
  }

  const getRiskBadgeStyle = (riskLevel) => {
    switch (riskLevel?.toLowerCase()) {
      case "critical":
        return "bg-red-100 text-red-800 border-red-300";
      case "high":
        return "bg-orange-100 text-orange-800 border-orange-300";
      case "medium":
        return "bg-yellow-100 text-yellow-800 border-yellow-300";
      case "low":
        return "bg-green-100 text-green-800 border-green-300";
      default:
        return "bg-gray-100 text-gray-800 border-gray-300";
    }
  };

  const parseJsonField = (field) => {
    if (!field) return [];
    if (typeof field === "string") {
      try {
        return JSON.parse(field);
      } catch {
        return field.split("\n").filter((item) => item.trim());
      }
    }
    return Array.isArray(field) ? field : [field];
  };

  const completedItems = parseJsonField(analysis.completed_items);
  const pendingItems = parseJsonField(analysis.pending_items);
  const detectedBlockers = parseJsonField(analysis.detected_blockers);

  return (
    <div className="bg-white rounded-lg border border-gray-200 p-6 space-y-6">
      <div className="flex items-start justify-between">
        <h3 className="text-lg font-semibold text-gray-900">AI Analysis</h3>
        <div className={`px-3 py-1 rounded-full border text-sm font-medium ${getRiskBadgeStyle(analysis.risk_level)}`}>
          {analysis.risk_level || "UNKNOWN"}
        </div>
      </div>

      {/* Summary */}
      {analysis.summary && (
        <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg">
          <p className="text-sm text-blue-900">{analysis.summary}</p>
          <p className="text-xs text-blue-700 mt-2 font-medium">
            Generated by: {analysis.ai_provider === "gemini" ? "Google Gemini" : "Rule-based Analysis"}
          </p>
        </div>
      )}

      {/* Risk Reason */}
      {analysis.risk_reason && (
        <div>
          <h4 className="text-sm font-medium text-gray-900 mb-2">Risk Assessment</h4>
          <p className="text-sm text-gray-700">{analysis.risk_reason}</p>
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {/* Completed Items */}
        {completedItems.length > 0 && (
          <div className="p-4 bg-green-50 border border-green-200 rounded-lg">
            <h4 className="text-sm font-medium text-green-900 mb-2">✓ Completed</h4>
            <ul className="text-sm text-green-800 space-y-1">
              {completedItems.map((item, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-green-600 font-bold mt-0.5">•</span>
                  <span>{typeof item === "string" ? item : item.name || item}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Pending Items */}
        {pendingItems.length > 0 && (
          <div className="p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
            <h4 className="text-sm font-medium text-yellow-900 mb-2">⏳ Pending</h4>
            <ul className="text-sm text-yellow-800 space-y-1">
              {pendingItems.map((item, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-yellow-600 font-bold mt-0.5">•</span>
                  <span>{typeof item === "string" ? item : item.name || item}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Detected Blockers */}
        {detectedBlockers.length > 0 && (
          <div className="p-4 bg-red-50 border border-red-200 rounded-lg">
            <h4 className="text-sm font-medium text-red-900 mb-2">⚠️ Blockers</h4>
            <ul className="text-sm text-red-800 space-y-1">
              {detectedBlockers.map((blocker, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-red-600 font-bold mt-0.5">•</span>
                  <span>{typeof blocker === "string" ? blocker : blocker.name || blocker}</span>
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>

      {/* Suggested Progress */}
      {analysis.suggested_progress && (
        <div className="p-4 bg-purple-50 border border-purple-200 rounded-lg">
          <h4 className="text-sm font-medium text-purple-900 mb-2">Suggested Progress</h4>
          <p className="text-sm text-purple-800">{analysis.suggested_progress}</p>
        </div>
      )}

      {/* Suggested Actions */}
      {analysis.suggested_actions && (
        <div className="p-4 bg-indigo-50 border border-indigo-200 rounded-lg">
          <h4 className="text-sm font-medium text-indigo-900 mb-2">Recommended Actions</h4>
          <p className="text-sm text-indigo-800">{analysis.suggested_actions}</p>
        </div>
      )}

      {/* Task Suggestions */}
      {analysis.task_suggestions && analysis.task_suggestions.length > 0 && (
        <div>
          <h4 className="text-sm font-medium text-gray-900 mb-3">Task Status Suggestions</h4>
          <div className="space-y-2">
            {(Array.isArray(analysis.task_suggestions)
              ? analysis.task_suggestions
              : typeof analysis.task_suggestions === "string"
                ? JSON.parse(analysis.task_suggestions)
                : []
            ).map((suggestion, idx) => (
              <div key={idx} className="p-3 bg-gray-50 border border-gray-200 rounded text-sm">
                <div className="font-medium text-gray-900">{suggestion.task_id || `Task ${idx + 1}`}</div>
                <div className="text-gray-600 text-xs mt-1">
                  Current: <span className="font-medium">{suggestion.current_status}</span> →{" "}
                  <span className="font-medium text-blue-600">{suggestion.suggested_status}</span>
                </div>
                {suggestion.reason && (
                  <div className="text-gray-600 text-xs mt-2">{suggestion.reason}</div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
