import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { aiApi } from "../../../api/ai";
import { Alert, Badge } from "../../../components/ui/Feedback";
import { Button } from "../../../components/ui/Button";

const tone = { critical: "danger", high: "danger", medium: "warning", low: "muted" };

function Metric({ label, value, detail }) {
  return (
    <div className="rounded-lg border border-line bg-white p-4">
      <p className="text-xs uppercase tracking-wider text-muted">{label}</p>
      <p className="font-display text-2xl font-semibold mt-2">{value}</p>
      <p className="text-xs text-muted mt-1">{detail}</p>
    </div>
  );
}

export default function AICommandCenterPage() {
  const [data, setData] = useState(null);
  const [error, setError] = useState("");
  const [simulation, setSimulation] = useState(null);
  const [simulating, setSimulating] = useState(false);
  const [scenario, setScenario] = useState("leave");
  const [selectedUser, setSelectedUser] = useState("");
  const [days, setDays] = useState(1);

  useEffect(() => {
    aiApi.commandCenter().then(setData).catch((err) => setError(err.message || "Could not load the AI Command Center."));
  }, []);

  if (error) return <Alert>{error}</Alert>;
  if (!data) return <p className="text-sm text-muted">Analyzing organization health…</p>;

  async function runSimulation(e) {
    e.preventDefault();
    setSimulating(true);
    setError("");
    try {
      setSimulation(await aiApi.simulate({ scenario, days: Number(days), user_id: Number(selectedUser) }));
    } catch (err) {
      setError(err.message || "Could not run the simulation.");
    } finally {
      setSimulating(false);
    }
  }

  return (
    <div className="space-y-6">
      <div>
        <p className="text-xs uppercase tracking-[0.18em] text-accent">AI Command Center</p>
        <h1 className="font-display text-2xl font-semibold tracking-tight mt-1">See what needs attention before it becomes urgent.</h1>
        <p className="text-sm text-muted mt-2">A live view built from project, task, quality, availability, and workload records.</p>
      </div>

      <section className="rounded-xl border border-line bg-ink text-white p-6">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div>
            <p className="text-[11px] uppercase tracking-[0.18em] text-white/50">Organization health</p>
            <p className="font-display text-5xl font-semibold mt-2">{data.organization_health == null ? "—" : `${data.organization_health}/100`}</p>
          </div>
          <Badge tone="accent">{data.provider === "gemini" ? "Generated by Gemini" : "Rule-based analysis"}</Badge>
        </div>
        <p className="max-w-3xl text-sm leading-6 text-white/80 mt-5">{data.summary}</p>
      </section>

      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
        <Metric label="Active employees" value={data.active_employee_count} detail="Current active accounts" />
        <Metric label="Projects" value={data.project_count} detail="Visible to organization admin" />
        <Metric label="Projects with risks" value={data.projects_with_risks} detail="Based on live signals" />
        <Metric label="Attention items" value={data.attention_items.length} detail="Sorted by severity" />
      </div>

      <section className="rounded-lg border border-line bg-white p-5">
        <div className="flex items-center justify-between gap-3 mb-4">
          <div><h2 className="font-semibold">What needs attention</h2><p className="text-xs text-muted mt-1">Recommendations are advisory. No project data is changed automatically.</p></div>
        </div>
        {data.attention_items.length === 0 ? <p className="text-sm text-muted">No active risk signals are currently detected.</p> : (
          <div className="space-y-2">
            {data.attention_items.map((item, index) => (
              <Link key={`${item.project_id}-${item.title}-${index}`} to={`/admin/projects/${item.project_id}`} className="flex items-start justify-between gap-4 rounded-md border border-line p-3 hover:bg-black/[0.02]">
                <div><p className="text-sm font-medium">{item.title}</p><p className="text-xs text-muted mt-1">{item.project_name} · {item.detail}</p></div>
                <Badge tone={tone[item.severity] || "muted"}>{item.severity}</Badge>
              </Link>
            ))}
          </div>
        )}
      </section>

      <section>
        <div className="flex items-end justify-between mb-3"><div><h2 className="font-semibold">Project health radar</h2><p className="text-xs text-muted mt-1">Transparent health scores from existing project intelligence.</p></div><Link className="text-xs text-accent hover:underline" to="/admin/workload">Open workload</Link></div>
        <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">
          {data.project_health.map((project) => (
            <Link key={project.project_id} to={`/admin/projects/${project.project_id}`} className="rounded-lg border border-line bg-white p-4 hover:border-accent/40 hover:shadow-sm transition-all">
              <div className="flex items-start justify-between gap-3"><div><p className="font-mono text-[11px] text-muted">{project.project_code}</p><h3 className="font-medium mt-1">{project.project_name}</h3></div><Badge tone={project.health_label === "healthy" ? "success" : project.health_label === "watch" ? "warning" : "danger"}>{project.overall_health}/100</Badge></div>
              <div className="grid grid-cols-2 gap-2 mt-4 text-xs text-muted"><span>Schedule {project.components.schedule}</span><span>Quality {project.components.quality}</span><span>Capacity {project.components.capacity}</span><span>Risks {project.risks.length}</span></div>
            </Link>
          ))}
          {!data.project_health.length && <p className="text-sm text-muted">No projects are available yet.</p>}
        </div>
      </section>

      <section className="rounded-lg border border-line bg-white p-5">
        <div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">AI What-If Simulator</h2><p className="text-xs text-muted mt-1">Explore an impact without changing assignments, leave, or project data.</p></div><Badge tone="accent">Simulation only</Badge></div>
        <form onSubmit={runSimulation} className="flex flex-col md:flex-row md:items-end gap-3 mt-4">
          <label className="flex-1 text-xs font-medium text-ink/70">Scenario<select className="mt-1 w-full rounded-md border border-line bg-white px-3 py-2 text-sm" value={scenario} onChange={(e) => setScenario(e.target.value)}><option value="leave">Employee takes leave</option></select></label>
          <label className="flex-1 text-xs font-medium text-ink/70">Employee<select className="mt-1 w-full rounded-md border border-line bg-white px-3 py-2 text-sm" value={selectedUser} onChange={(e) => setSelectedUser(e.target.value)} required><option value="">Select employee</option>{data.team_workload.map((member) => <option key={member.user_id} value={member.user_id}>{member.full_name}</option>)}</select></label>
          <label className="w-full md:w-28 text-xs font-medium text-ink/70">Days<input className="mt-1 w-full rounded-md border border-line bg-white px-3 py-2 text-sm" type="number" min="1" max="30" value={days} onChange={(e) => setDays(e.target.value)} /></label>
          <Button type="submit" disabled={simulating}>{simulating ? "Simulating…" : "Run simulation"}</Button>
        </form>
        {simulation && <div className="mt-4 rounded-md border border-accent/20 bg-accent/[0.04] p-4"><div className="flex items-center justify-between gap-3"><p className="text-sm font-medium">{simulation.label}</p><button className="text-xs text-muted hover:text-ink" onClick={() => setSimulation(null)}>Dismiss</button></div><div className="grid grid-cols-2 gap-3 mt-3 text-sm"><div><p className="text-xs text-muted">Current</p><p className="font-medium">{simulation.current.capacity_hours}h · {simulation.current.utilization_percent ?? "—"}% · {simulation.current.risk}</p></div><div><p className="text-xs text-muted">Predicted</p><p className="font-medium">{simulation.predicted.capacity_hours}h · {simulation.predicted.utilization_percent ?? "—"}% · {simulation.predicted.risk}</p></div></div><p className="text-xs text-muted mt-3">Affected tasks: {simulation.affected_tasks.length}. {simulation.recommendation}</p></div>}
      </section>
    </div>
  );
}