from datetime import date, datetime

from pydantic import BaseModel, EmailStr, ConfigDict

from app.models.role import RoleEnum


class EmployeeCreateRequest(BaseModel):
    """What the Admin fills in when creating an employee. Note: no company
    email or password field -- both are generated by the backend."""
    first_name: str
    last_name: str
    employee_id: str
    role: RoleEnum
    department: str | None = None
    personal_email: EmailStr  # any valid provider, not restricted to Gmail
    phone: str | None = None
    skills: str | None = None
    experience: str | None = None
    joining_date: date | None = None


class GeneratedEmailPreview(BaseModel):
    """Returned by the preview endpoint so the Admin can see the company
    email SprintNova would generate before confirming creation (spec §18)."""
    company_email: str


class EmployeeCreateResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    employee_id: str
    first_name: str
    last_name: str
    personal_email: EmailStr
    company_email: str
    role: RoleEnum
    department: str | None
    is_active: bool
    must_change_password: bool
    created_at: datetime


class EmployeeListItem(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    employee_id: str
    first_name: str
    last_name: str
    company_email: str
    personal_email: EmailStr
    role: RoleEnum
    department: str | None
    is_active: bool


class EmployeeStatusUpdate(BaseModel):
    is_active: bool
